#!/usr/bin/env bash

if [ ! -f install ]; then
	echo 'install must be run within its container folder' 1>&2
	exit 1
fi

if [ "$1" == '' ]; then
	echo 'usage: ./install project-name' 1>&2
	exit 1
fi

CURDIR=`pwd`
OLDGOPATH="$GOPATH"
OLDGOBIN="$GOBIN"
export GOPATH="$CURDIR"
export GOBIN=""

gofmt -tabs=true -tabwidth=4 -w src

go install $1

export GOPATH="$OLDGOPATH"
export GOBIN="$OLDGOBIN"

echo 'finished'